### PR TITLE
Wrong parsing result with decimals like 1.8

### PR DESCRIPTION
**Pull request by andreaswatch**
Get Value of '1.8' instead of '18'
Sample:
#37=VECTOR($,#118,1.8);

### CODE REVIEW

**Comment by brettfo** [comment]
Could you add a unit test to ensure this doesn't regress?  I did something similar in my [Dxf](https://github.com/IxMilia/Dxf) library where I explicitly try to parse a `double` in a culture that uses a comma as a decimal separator ("de-DE").  See [this](https://github.com/IxMilia/Dxf/blob/master/src/IxMilia.Dxf.Test/DxfReaderWriterTests.cs#L1189) for an example.

**Comment by brettfo** [comment]
Also, could you update the `int.Parse()` on the line below, too?

**Comment by andreaswatch** [comment]
I'll do that, but it will take a few days until I find enough time.

**Comment by brettfo** [comment]
Merged in 3c7085b5230957f6b2123ff8e614be133ef98394.

**Pull request closed without merging**
